name: Deploy

on:
  push:
    tags:
      - '**'
  workflow_dispatch: # so we can trigger it from another workflow or manually

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:25.08
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # flatter doesn't handle this for some reason
      - name: Install runtime dependency
        run: |
          runtime_name="$(grep 'base:' io.wowup.WowUp.yml | awk '{print $2}')"
          runtime_version="$(grep 'base-version:' io.wowup.WowUp.yml | awk '{print $2}')"
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install --user --noninteractive flathub "${runtime_name}/x86_64/${runtime_version//\'/}"

      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            io.wowup.WowUp.yml
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-pages-artifact: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
